# Generated by Django 3.0 on 2020-01-15 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Surname')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to=my_app.models.upload_location, verbose_name='Image')),
                ('desc', models.TextField(blank=True, max_length=150, verbose_name='Description')),
                ('thumbnail', models.ImageField(upload_to=my_app.models.thumbnail_location, verbose_name='Thumbnail')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date of image uploaded')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of image updated')),
                ('public', models.BooleanField(verbose_name='Publicity of image')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
